# Generated by Django 2.2 on 2019-05-18 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='link',
            name='category',
        ),
    ]
