# Generated by Django 2.2 on 2019-05-19 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_auto_20190519_0158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
