# Generated by Django 2.2 on 2019-05-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0004_delete_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='space_host'),
        ),
    ]
