# Generated by Django 2.2 on 2019-05-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0005_space_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilehost',
            name='type',
            field=models.CharField(blank=True, choices=[('Association', 'Association'), ('Center', 'Center'), ('Club', 'Club'), ('Community', 'Community'), ('Company', 'Company'), ('Cooperative/Collective', 'Cooperative/Collective'), ('Farm/Finca', 'Farm/Finca'), ('Government/Town Council/Village', 'Government/Town Council/Village'), ('Institute', 'Institute'), ('Museum', 'Museum'), ('NGO/Foundation', 'NGO/Foundation'), ('Park', 'Park'), ('Political Party', 'Political Party'), ('School/Nursery/Kindergarten', 'School/Nursery/Kindergarten'), ('Social Enterprise', 'Social Enterprise'), ('Society', 'Society'), ('Station & Network', 'Station & Network'), ('Support Group', 'Support Group'), ('Union', 'Union'), ('University', 'University'), ('Others', 'Others')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='frequency',
            field=models.CharField(choices=[('Once', 'Once'), ('Multiple', 'Multiple'), ('Fexible', 'Fexible')], max_length=30),
        ),
        migrations.AlterField(
            model_name='program',
            name='type',
            field=models.CharField(choices=[('Course', 'Course'), ('Consultation', 'Consultation'), ('Lecture', 'Lecture'), ('Show', 'Show'), ('Talk', 'Talk'), ('Workshop', 'Workshop'), ('Others', 'Others')], max_length=30),
        ),
    ]
