# Generated by Django 2.2.2 on 2019-06-30 07:58

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0007_auto_20190605_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletraveler',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
