# Generated by Django 2.2.2 on 2019-06-30 14:04

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0008_auto_20190630_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilehost',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
