# Generated by Django 2.2 on 2019-05-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='available',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='space_host'),
        ),
    ]
