# Generated by Django 2.2 on 2019-05-28 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_available_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='available',
            name='photo',
        ),
    ]
